camera_id = 1
camera_name = Camera Depan
netcam_url = http://192.168.101.6/video.mjpg
# Sesuaikan user/pass jika kamera membutuhkan auth
# netcam_user = admin
# netcam_pass = password_kamera
target_dir = /var/lib/motioneye
width = 1280
height = 720
framerate = 10
text_left = CAM 1
text_right = %Y-%m-%d %T
movie_codec = mp4
movie_fps = 10
movie_quality = 75
emulate_motion = true
threshold = 1500
event_gap = 60
output_pictures = off
output_debug_pictures = off
